DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS students CASCADE;

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    patronymic VARCHAR(50),
    group_name VARCHAR(50) NOT NULL
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    upload_date TIMESTAMP NOT NULL
);

CREATE INDEX idx_documents_student_id ON documents(student_id);
CREATE INDEX idx_students_last_name ON students(last_name);
