DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS status CASCADE;

CREATE TABLE status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    file_size BIGINT NOT NULL,
    file_format VARCHAR(10) NOT NULL,
    status_id BIGINT REFERENCES status(id) ON DELETE CASCADE,
    error_message VARCHAR(255)
);

INSERT INTO status (status_name) VALUES ('SUCCESS'), ('FAILED');

CREATE UNIQUE INDEX idx_reports_document_id ON reports(document_id);
CREATE INDEX idx_reports_status_id ON reports(status_id);